<form action="" method="post">
    <div class="row">
        <div class="col-md-6">
            <label for="nome">
                <input type="text" name="nome" placeholder="Nome">
            </label>
        </div>
        <div class="col-md-6">
            <label for="email">
                <input type="email" name="email" placeholder="Email">
            </label>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <label for="">
                <input type="password" name="senha" placeholder="Senha">
            </label>
        </div>
        <div class="col-md-6">
            <label for="checked_yes">
                <input type="radio" id="checked_yes" name="active" checked value="1">
                <span>Sim</span>
            </label>
            <label for="checked_no">
                <input type="radio" id="checked_no" name="active" value="0">
                <span>Não</span>
            </label>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <label for="">
                <button>
                    <i class="glyphicon glyphicon-ok"></i>&nbsp;
                    Adicionar
                </button>
            </label>
        </div>
        <div class="col-md-9 message">
            <?php if ($this->reply): ?>
                <?php echo $this->reply ?>
            <?php endif; ?>
        </div>
    </div>
</form>