<div class="row">
    <div class="col-md-6">
        <h1>Register User</h1>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consectetur dolor dolore error exercitationem fugiat
            iure iusto maxime, molestiae necessitatibus nemo non nostrum odit optio pariatur, perspiciatis rerum, vitae?
            Impedit.
        </p>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consectetur dolor dolore error exercitationem fugiat
            iure iusto maxime, molestiae necessitatibus nemo non nostrum odit optio pariatur, perspiciatis rerum, vitae?
            Impedit.
        </p>
    </div>
    <div class="col-md-6">
        <h1>Manage User</h1>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consectetur dolor dolore error exercitationem fugiat
            iure iusto maxime, molestiae necessitatibus nemo non nostrum odit optio pariatur, perspiciatis rerum, vitae?
            Impedit.
        </p>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consectetur dolor dolore error exercitationem fugiat
            iure iusto maxime, molestiae necessitatibus nemo non nostrum odit optio pariatur, perspiciatis rerum, vitae?
            Impedit.
        </p>
    </div>
</div>